# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.11.150"
    master.vm.hostname = "master"
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.11.151"
    slave.vm.hostname = "slave"
  end

end
